name: jd_rl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - ipywidgets
  - pylint
  - rope
  - nodejs
  - pillow
  - pytorch>=1.8.1
  - torchvision
  - gym
  - matplotlib
  - wandb
