hydra:
  run:
    dir: outputs/${hydra.job.name}
  output_subdir: "config"
  job:
    name: ${parse_string:${run.name}}

defaults:
  - defaults/environment
  - defaults/nodes
  - defaults/callbacks
  - defaults/model
  - defaults/run
  - runs/test_run # use +runs=test as command line argument
